{"package_name": "java.lang.reflect", "subclass_list": [], "class_description": "InvocationTargetException is a checked exception that wraps\n an exception thrown by an invoked method or constructor. As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"target exception\"\n that is provided at construction time and accessed via the\n getTargetException() method is now known as the cause,\n and may be accessed via the Throwable#getCause() method,\n as well as the aforementioned \"legacy method.\" ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["ReflectiveOperationException"], "Methods": [{"params": [{"param_name": ["target"], "param_type": "Throwable", "param_description": " the target exception"}], "class_name": "InvocationTargetException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a InvocationTargetException with a target exception.\n", "method_declar": ""}, {"params": [{"param_name": ["target"], "param_type": "Throwable", "param_description": " the target exception"}, {"param_name": ["s"], "param_type": "String", "param_description": " the detail message"}], "class_name": "InvocationTargetException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a InvocationTargetException with a target exception\n and a detail message.\n", "method_declar": ""}, {"params": [], "class_name": "InvocationTargetException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the cause of this exception."], "return_type": ["Throwable"]}, "method_name": "getCause", "method_description": "Returns the cause of this exception (the thrown target exception,\n which may be null).\n", "method_declar": ""}, {"params": [], "class_name": "InvocationTargetException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the thrown target exception (cause of this exception)."], "return_type": ["Throwable"]}, "method_name": "getTargetException", "method_description": "Get the thrown target exception.\n\n \nThis method predates the general-purpose exception chaining facility.\n The Throwable#getCause() method is now the preferred means of\n obtaining this information.\n", "method_declar": ""}], "class_name": "InvocationTargetException", "Vars": null}