{"package_name": "java.lang", "subclass_list": [], "class_description": "Thrown when an application tries to load in a class through its\n string name using: but no definition for the class with the specified name could be found. As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"optional exception\n that was raised while loading the class\" that may be provided at\n construction time and accessed via the getException() method is\n now known as the cause, and may be accessed via the Throwable#getCause() method, as well as the aforementioned \"legacy method.\" ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["ReflectiveOperationException"], "Methods": [{"params": [], "class_name": "ClassNotFoundException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a ClassNotFoundException with no detail message.\n", "method_declar": ""}, {"params": [{"param_name": ["s"], "param_type": "String", "param_description": " the detail message."}], "class_name": "ClassNotFoundException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a ClassNotFoundException with the\n specified detail message.\n", "method_declar": ""}, {"params": [{"param_name": ["s"], "param_type": "String", "param_description": " the detail message"}, {"param_name": ["ex"], "param_type": "Throwable", "param_description": " the exception that was raised while loading the class"}], "class_name": "ClassNotFoundException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a ClassNotFoundException with the\n specified detail message and optional exception that was\n raised while loading the class.\n", "method_declar": ""}, {"params": [], "class_name": "ClassNotFoundException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the cause of this exception."], "return_type": ["Throwable"]}, "method_name": "getCause", "method_description": "Returns the cause of this exception (the exception that was raised\n if an error occurred while attempting to load the class; otherwise\n null).\n", "method_declar": ""}, {"params": [], "class_name": "ClassNotFoundException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the Exception that was raised while loading a class"], "return_type": ["Throwable"]}, "method_name": "getException", "method_description": "Returns the exception that was raised if an error occurred while\n attempting to load the class. Otherwise, returns null.\n\n \nThis method predates the general-purpose exception chaining facility.\n The Throwable#getCause() method is now the preferred means of\n obtaining this information.\n", "method_declar": ""}], "class_name": "ClassNotFoundException", "Vars": null}