{"package_name": "java.lang", "subclass_list": ["ZipError", "ZipError"], "class_description": "Thrown to indicate some unexpected internal error has occurred in\n the Java Virtual Machine. ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["VirtualMachineError"], "Methods": [{"params": [], "class_name": "InternalError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an InternalError with no detail message.\n", "method_declar": ""}, {"params": [{"param_name": ["message"], "param_type": "String", "param_description": " the detail message."}], "class_name": "InternalError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an InternalError with the specified\n detail message.\n", "method_declar": ""}, {"params": [{"param_name": ["message"], "param_type": "String", "param_description": " the detail message (which is saved for later retrieval\n         by the Throwable.getMessage() method)."}, {"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method).  (A null value is\n         permitted, and indicates that the cause is nonexistent or\n         unknown.)"}], "class_name": "InternalError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an InternalError with the specified detail\n message and cause.  \nNote that the detail message associated\n with cause is not automatically incorporated in\n this error's detail message.\n", "method_declar": ""}, {"params": [{"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method).  (A null value is\n         permitted, and indicates that the cause is nonexistent or\n         unknown.)"}], "class_name": "InternalError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an InternalError with the specified cause\n and a detail message of (cause==null ? null :\n cause.toString()) (which typically contains the class and\n detail message of cause).\n", "method_declar": ""}], "class_name": "InternalError", "Vars": null}